### ISSUE TITLE
BMW M4 4 deurs

### ISSUE THREAD

**Issue by WillemHoeksteen** [Ballenbakpoeper/MRP-Car-ToDo#12]
Ik vind eig dat de BMW M4 4 deurs moet zijn of dat je in 4 stoelen kan zitten want er zitten ook 2 stoelen achter en daar kan je nu niet in. best wel zonde eigenlijk

**Comment by Ballenbakpoeper** [comment]
Ik weet niet zeker of dit mogelijk is.

Deur 3 4 zijn de spiegels namelijk en ik weet niet of ik extra seats bij kan maken. Ik ga voor je kijken.

**Comment by WillemHoeksteen** [comment]
Oh, helemaal goed.. ik hoor het wel!
