### ISSUE TITLE
Crash van een MRP Dono Pack

### ISSUE THREAD

**Issue by Fernandoxtm** [Ballenbakpoeper/MRP-Car-ToDo#13]
![kutcrash](https://github.com/Ballenbakpoeper/MRP-Car-ToDo/assets/139654663/92af20f5-2a93-4323-b3dd-0f3b232f7e9f)
deze crash maakt mijn hoofd moe man, hoop dat je het kan oplossen bro!

**Comment by Ballenbakpoeper** [comment]
Dit zou morgen ochtend na de restart opgelost zijn.

**Comment by Ballenbakpoeper** [comment]
Als de restart van 23:00 is geweest nu al.
