### ISSUE TITLE
Miss goeie donatie-auto's verhandelbaar maken?

### ISSUE THREAD

**Issue by WillemHoeksteen** [Ballenbakpoeper/MRP-Car-ToDo#7]
Want nu zijn er echt weinig goeie autos te verkrijgen als je geen irl geld wilt spenderen en soms is het een beetje irritant want dan heb je zelf een auto voor 4milljoen gekocht en dan gaat een donatie auto 10x zo hard

**Comment by WillemHoeksteen** [comment]
zou chill zijn

**Comment by Ballenbakpoeper** [comment]
Dit is geen bug. Hier kan ik niks mee momenteel.
